name: zero_waste_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  url_launcher: ^6.3.0
  fl_chart: ^0.66.1
  conditional_builder_null_safety: ^0.0.6
  smooth_page_indicator: ^1.1.0
  device_preview: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  icons_plus: ^5.0.0
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.6

  
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # to declare package to change app icon 
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

# to make icon change in android and IOS
flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  # App Icon path 
  image_path: "assets/images/app.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/images/onboarding/  
    - assets/images/home/  
    - assets/images/home/profile/  
    - assets/images/home/plastics/  
    - assets/images/home/glass/  
    - assets/images/home/metal/  
    - assets/images/home/paper/  
    - assets/images/authentication/
    - assets/icons/


fonts:
  - family: Outfit
    fonts:
      - asset: assets/fonts/Outfit/Outfit-Black.ttf
        weight: 900
      - asset: assets/fonts/Outfit/Outfit-Bold.ttf
        weight: 700
      - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Outfit/Outfit-Light.ttf
        weight: 300
      - asset: assets/fonts/Outfit/Outfit-Medium.ttf
        weight: 500
      - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        weight: 400
      - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Outfit/Outfit-Thin.ttf
        weight: 100

# flutter_assets:
#   assets_path: assets/images/onboarding/
#   output_path: lib/shared/
#   filename: assets.dart
#   field_prefix:

flutter_assets:
  assets_path: assets/
  output_path: lib/shared/
  filename: assets.dart
  field_prefix:
